import Idiot from "./img/Idiot.webp"
import dochka from "./img/dochka.jpeg"
import vechera from  "./img/vechera.jpg"
import dusha from "./img/dusha.jpg"
import revizor from "./img/revizor.jpg"
import taras from "./img/taras.jpg"
import mir from "./img/mir.jpg"
import dub from "./img/dub.jpg"
import onegin from  "./img/onegin.jpg"
import utro from "./img/utro.jpg"
import smotritel from "./img/smotritel.jpg"
import shinel from "./img/shinel.jpg"
import carevna from "./img/carevna.jpeg"
import nakazanie from "./img/nakazanie.jpg"
import besi from "./img/besi.jpg"
import doctor from "./img/doctor.jpg"
import medved from "./img/medved.jpg"
import chinovnik from "./img/chinovnik.jpg"
import hamelion from "./img/hamelion.jpg"
import geroi from "./img/geroi.jpg"

export const BOOKS = {besi, Idiot, dochka, vechera, dusha, revizor, taras, mir, dub, onegin, utro, smotritel, shinel, carevna, nakazanie, doctor, medved, chinovnik, hamelion, geroi}
